<template>
  <div class="free-model-page">
    <div class="free-model-banner">
      <div class="banner-pic">
        <img :src="headerImg" />
      </div>
      <div class="banner-text">
        <div class="banner-title" :class="`${lang}`">
          {{ isZh ? "超写实人物模型商城" : "PEOPLEGROUNDTRUTH" }}
        </div>
        <div class="banner-subtitle">
          {{
            isZh
              ? "向你推荐次时代\n超写实扫描人物模型"
              : "Recommended for next-gen\nUltra-Realistic Scanning\nCharacter Models"
          }}
        </div>
      </div>
    </div>
    <div class="multi-model-wrap">
      <div class="title">
        {{
          isZh
            ? "选择最契合的写实人物模型"
            : "Select Realistic Character Models"
        }}
      </div>
      <div class="sub-title">
        {{
          isZh
            ? "网站包含大量3D扫描模特数据素材数量多、姿势丰富，可根据您的需求进行筛选。\n包含不同场景 年龄 风格的人物数据"
            : "Includes a large number of 3D scanned model data with a large number of\nposes, which can be filtered according to your needs.\nContains character data for different scenes, ages and styles."
        }}
      </div>
      <div class="tab-list">
        <div
          class="tab-item"
          v-for="(item, idx) in tabList"
          :class="`${idx == activeTab ? 'active' : ''}`"
          :key="item?.id"
          @click="tabChange(item, idx)"
        >
          {{ item?.[`name${lang}`] }}
        </div>
      </div>
      <div class="tab-content">
        <div
          class="tab-content-item"
          v-for="tabItem in activeList"
          :key="tabItem?.id"
        >
          <div class="item-pic">
            <img
              :src="`${require(`@/assets/imgs/freeModel/style-${tabItem?.id}.png`)}`"
              alt=""
            />
          </div>
          <div class="item-name">{{ tabItem?.[`name${lang}`] }}</div>
        </div>
      </div>
    </div>
    <div class="free-wrap">
      <div class="free-text">
        <div class="desc-one" :class="`${lang}`">
          {{
            isZh
              ? "现在点击下载\n免费的样例模型\n开启你的超写实渲染之路"
              : "Click to download\nFree Sample Models\nStart your way to hyper-realistic rendering"
          }}
        </div>
        <div class="desc-second">
          {{
            isZh
              ? "矩阵相机生成的超写实三维人物模型，帮您省下寻找<\n高清素材的精力。使画面更真实、更高清、更有冲击力。\n现在就点击下载，来试试扫描超写实模型。"
              : "The ultra-realistic 3D character models\ngenerated by Matrix Camera help you save your\nefforts in finding HD materials. Make the image\nmore realistic, HD and impactful.\nClick download now to try scanning ultra-realistic models."
          }}
        </div>
        <div class="download-btn">
          {{ isZh ? "点击下载 免费样例" : "Click to download free samples" }}
        </div>
        <div class="free-pic-list1">
          <div class="list1-item" v-for="item in list1">
            <div class="title">{{ item?.[`title${lang}`] }}</div>
            <div class="text">{{ item?.[`text${lang}`] }}</div>
          </div>
        </div>
      </div>
      <div class="free-pic">
        <img :src="imgUrl" />
      </div>
    </div>
    <div class="free-model-materials">
      <div class="materials-detail">
        <div class="detail-item" v-for="item in list2" :key="item?.id">
          <div v-for="listItem in item?.[`${$i18n.locale}List`]">
            {{ listItem }}
          </div>
        </div>
      </div>
    </div>
    <div class="more-model">
      <div class="title">
        {{
          isZh
            ? "大量扫描模型持续更新"
            : "A large number of scanned models are continuously updated"
        }}
      </div>
      <div class="more-desc">
        {{
          isZh
            ? "拥有超过8000个模型资源， 涵盖不同年龄 不同场景不同风格的人物数据。根据\n您的需求正在不断更新中……"
            : "There are more than 8000 models covering different ages, different scenes and different\nstyles of characters. According to your demand is constantly updating ......"
        }}
      </div>
      <div class="more-pic">
        <img :src="imgUrl" alt="" />
      </div>
    </div>
  </div>
</template>

<script>
import Img1 from "@/assets/imgs/test/1.jpg";
import Img2 from "@/assets/imgs/freeModel/free_01.png";

export default {
  data() {
    return {
      imgUrl: Img1,
      headerImg: Img2,
      activeTab: 0,
      tabList: [
        {
          id: 1,
          nameZh: "多场景人物数据",
          nameEn: "Multi-scene character",
          list: [
            { id: "1-1", nameZh: "校园", nameEn: "School style" },
            { id: "1-2", nameZh: "运动", nameEn: "Sporty style" },
            { id: "1-3", nameZh: "生活", nameEn: "Casual style" },
            { id: "1-4", nameZh: "商务", nameEn: "Business style" },
            { id: "1-5", nameZh: "艺术", nameEn: "Artistic style" },
          ],
        },
        {
          id: 2,
          nameZh: "多姿态 服饰 造型数据",
          nameEn: "Multi-style Clothing",
          list: [
            { id: "2-1", nameZh: "A-POSE", nameZh: "A-POSE" },
            {
              id: "2-2",
              nameZh: "多姿态 服饰 造型",
              nameZh: "Multi-style Clothing Style",
            },
          ],
        },
        {
          id: 3,
          nameZh: "多年龄段分布数据",
          nameEn: "Multi-age distribution",
          list: [
            { id: "3-1", nameZh: "儿童", nameZh: "Children" },
            { id: "3-2", nameZh: "老中青年", nameZh: "A-POSE" },
          ],
        },
        {
          id: 4,
          nameZh: "多地域、 民族、 肤色数据",
          nameEn: "Multiregional composition",
          list: [
            {
              id: "4-1",
              nameZh: "中国（多民族造型）",
              nameZh: "China (Multi-ethnic style)",
            },
            { id: "4-2", nameZh: "其他地区", nameZh: "Other regions" },
          ],
        },
      ],
      activeList: [],
      list1: [
        {
          id: 1,
          titleZh: "4K和8K纹理贴图",
          titleEn: "4K and 8K texture",
          textZh: "贴图经过专业校色，还原真实的\n纹理细节，提供3套服装颜色选择",
          textEn:
            "The mapping has been professionally\ncolor-corrected to restore the real\ntexture details, providing 3 sets of\nclothing color options",
        },
        {
          id: 1,
          titleZh: "三万面、十万面模型",
          titleEn: "30K & 100K mesh",
          textZh: "由300万面模型优化得到的模\n型，可根据算力情况选用。",
          textEn:
            "The model obtained from the optimization of the 3 million surface model can be selected according to the performance.",
        },
        {
          id: 1,
          titleZh: "细节法线贴图",
          titleEn: "Normal mapping",
          textZh: "保留原始模型上最真实的细\n节，让模型渲染更逼真",
          textEn:
            "Preserve the most realistic\ndetails on the original model for\nmore lifelike model rendering",
        },
        {
          id: 1,
          titleZh: "划分材质Mask贴图",
          titleEn: "Detalied Mask",
          textZh: "通过遮罩贴图，轻松控制模\n型不同位置的材质效果。",
          textEn:
            "Easily control the material effects\nat different locations of the model\nthrough mask mapping.",
        },
      ],
      list2: [
        {
          id: 1,
          ZhList: [
            "全身姿态模型\n¥129",
            "三万面 模型",
            "4K贴图",
            "颜色贴图  、法线贴图",
            "--",
          ],
          EnList: [
            "Whole body posture model\n$ 19.9",
            "30K mesh",
            "4K Tex",
            "Diffuse Mapping、 Normal Mapping",
            "-",
          ],
        },
        {
          id: 2,
          ZhList: [
            "全身高精度姿态模型\n¥199",
            "三万面和十万面的模型",
            "4K 8K贴图",
            "三张颜色贴图  、法线贴图",
            "Mask 遮罩贴图",
          ],
          EnList: [
            "HD model of whole body model\n$ 29.9",
            "30K & 100K mesh",
            "4K 8K Tex",
            "Diffuse Mapping × 3 \nNormal Mapping",
            "Detalied Mask",
          ],
        },
      ],
    };
  },
  computed: {
    isZh() {
      return this.$i18n.locale === "Zh";
    },
    lang() {
      return this.$i18n.locale;
    },
  },
  methods: {
    tabChange(item, idx) {
      this.activeTab = idx;
      this.activeList = [...item?.list];
    },
  },
  created() {
    this.activeList = [...this.tabList?.[0].list];
  },
};
</script>
<style lang="less" scoped>
.free-model-page {
  .free-model-banner {
    position: relative;
    display: flex;
    justify-content: center;
    width: 100%;
    height: 600px;
    background-color: #242424;
    .banner-pic {
      height: 100%;
      img {
        display: block;
        height: 100%;
      }
    }
    .banner-text {
      position: absolute;
      left: 50%;
      top: 40%;
      transform: translate(-50%, -50%);
      color: #fff;
      .banner-title {
        font-weight: bold;
        font-size: 70px;
        line-height: 129px;
        letter-spacing: 40px;
        text-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
        text-align: center;
        white-space: nowrap;
        &.En {
          letter-spacing: 10px;
          font-size: 50px;
        }
      }
      .banner-subtitle {
        font-size: 25px;
        line-height: 40px;
        white-space: pre-wrap;
      }
    }
  }
  .multi-model-wrap {
    padding: 70px 140px 120px;
    background-color: #242424;
    color: #fff;
    .title {
      font-weight: bold;
      font-size: 40px;
      line-height: 60px;
      letter-spacing: 3px;
    }
    .sub-title {
      margin-top: 20px;
      font-size: 20px;
      letter-spacing: 1px;
      line-height: 30px;
      white-space: pre-wrap;
    }
    .tab-list {
      display: flex;
      align-items: center;
      justify-content: space-around;
      margin-top: 60px;
      .tab-item {
        display: flex;
        align-items: center;
        justify-content: center;
        height: 50px;
        padding: 0 30px;
        color: #000;
        background-color: #fff;
        border-radius: 12px;
        font-size: 18px;
        font-weight: 500;
        cursor: pointer;
        &.active {
          color: #fff;
          background-color: #ed6336;
        }
      }
    }
    .tab-content {
      display: flex;
      align-items: center;
      justify-content: center;
      height: 300px;
      margin: 60px auto 0;
      border-radius: 15px;
      background-color: #fff;
      min-width: 500px;
      .tab-content-item {
        color: #222;
        margin-right: 60px;
        &:last-child {
          margin-right: 0px;
        }
        .item-pic {
          height: 200px;
          img {
            height: 100%;
          }
        }
        .item-name {
          margin-top: 20px;
          text-align: center;
        }
      }
    }
  }
  .free-wrap {
    display: flex;
    justify-content: space-between;
    background-color: #242424;
    color: #fff;
    .free-text,
    .free-pic {
      flex: 1;
      flex-shrink: 0;
    }
    .free-text {
      padding-left: 160px;
      color: #fff;
      .desc-one {
        font-weight: bold;
        font-size: 40px;
        line-height: 60px;
        letter-spacing: 3px;
        white-space: pre-wrap;
        &.En {
          letter-spacing: 0;
        }
      }
      .desc-second {
        margin-top: 80px;
        font-size: 20px;
        line-height: 30px;
        white-space: pre-wrap;
      }
      .download-btn {
        display: flex;
        align-items: center;
        justify-content: center;
        width: 300px;
        height: 60px;
        margin-top: 60px;
        background: #ed6336;
        border-radius: 12px;
        cursor: pointer;
        font-weight: bold;
      }
      .free-pic-list1 {
        position: relative;
        display: flex;
        flex-wrap: wrap;
        margin-top: 50px;
        width: 112%;
        z-index: 1;
        .list1-item {
          width: 45%;
          padding: 25px;
          margin: 0 15px 50px 0;
          border-radius: 12px;
          color: #000;
          background-color: #fff;
          .title {
            font-size: 28px;
            font-weight: bold;
          }
          .text {
            margin-top: 10px;
            font-size: 18px;
            white-space: pre-wrap;
          }
        }
      }
    }
    .free-pic {
      img {
        display: block;
        width: 100%;
      }
    }
  }
  .free-model-materials {
    padding: 0 150px 40px;
    background-color: #242424;
    .materials-detail {
      height: 200px;
      background-color: #fff;
      border-radius: 12px;
      overflow: hidden;
      .detail-item {
        display: flex;
        height: 50%;
        justify-content: space-between;
        border-bottom: 1px solid #6b6b6b;
        &:last-child {
          border-bottom: none;
        }
        & > div {
          display: flex;
          align-items: center;
          justify-content: center;
          text-align: center;
          flex: 1;
          flex-shrink: 0;
          color: #000;
          font-size: 14px;
          font-weight: bold;
          white-space: pre-wrap;
          &:nth-child(odd) {
            background-color: #f5f5f5;
          }
          &:nth-child(1) {
            background-color: #d9d9d9;
          }
        }
        &:nth-child(2) {
          & > div {
            &:nth-child(1) {
              color: #fff;
              background-color: #ed6336;
            }
          }
        }
      }
    }
  }
  .more-model {
    padding-top: 50px;
    color: #000;
    background-color: #ddd;
    .title {
      padding-left: 150px;
      font-weight: bold;
      font-size: 50px;
      line-height: 60px;
      letter-spacing: 3px;
      white-space: pre-wrap;
    }
    .more-desc {
      padding-left: 150px;
      margin-top: 20px;
      font-size: 16px;
      line-height: 28px;
      white-space: pre-wrap;
    }
    .more-pic {
      display: flex;
      justify-content: center;
      height: 300px;
      margin-top: 20px;
      img {
        display: block;
        height: 100%;
      }
    }
  }
}
</style>
